# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
ko_fi: # Replace with a single Ko-fi username
custom: ['https://paypal.me/revGSM']
custom1: ['https://pcgame.gitlab.io']
custom: ['https://retroarchemu.gitlab.io']
custom: ['https://AetherSX2EmuPS2.gitlab.io']
custom: ['https://citraemulator.gitlab.io']
custom: ['https://DraSticDSEmulator.gitlab.io']
custom: ['https://kernelsu.gitlab.io']
custom: ['https://magiskmodule.gitlab.io']
custom: ['https://majorgeeks.gitlab.io']
custom: ['https://makeuseof.gitlab.io']
custom: ['https://OceanofGames.gitlab.io']
custom: ['https://pspemu.gitlab.io']
custom: ['https://rpcs3.gitlab.io']

